language: php

dist: bionic

php: 
- 8.0

services:
- mysql

before_script:
- cp .env.example .env
- mysql -e "create database prueba"
- composer self-update
- composer install --no-interaction --prefer-source
- php artisan key:generate
- php artisan migrate

script:
- vendor/bin/phpunit